---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-service
spec:
  selector:
    matchLabels:
      app: card-service
  replicas: 1
  template:
    metadata:
      labels:
        app: card-service
    spec:
      containers:
      - name: card-service
        image: denys8herasymuk/web-banking-card-service:0.1
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8006