import os
from dotenv import load_dotenv


DEBUG_MODE = True

load_dotenv("request_generator.env")

REGISTRATION_REQUEST = 'REGISTRATION_REQUEST'
MONEY_REQUEST = 'MONEY_REQUEST'
TOPUP_REQUEST = 'TOPUP_REQUEST'
TRANSACTION_REQUEST = 'TRANSACTION_REQUEST'

REGISTRATION_ENDPOINT = os.getenv('REGISTRATION_ENDPOINT')
TRANSACTION_ENDPOINT = os.getenv('TRANSACTION_ENDPOINT')
TOPUP_ENDPOINT = os.getenv('TOPUP_ENDPOINT')
GENERATOR_TOKEN = os.getenv('GENERATOR_TOKEN')
USER_CARDS = os.getenv('USER_CARDS').split(',')
